version: '3'


services:
  mlab_mongo:
    image: mongo
    container_name: mlab_mongo
    volumes:
      - /data/mlab/db/mongo
    networks:
      - nginx-proxy
    ports:
      - "27017:27017"

  mlab_init_mongo:
    image: mongo
    container_name: mlab_init_mongo
    working_dir: /var/tmp
    environment:
      DATABASE_MAME: "mlab"
      MLAB_MONGO_HOST: mlab_mongo
    volumes:
      - ./script/:/var/tmp
      - ./asserts/mlab/:/var/tmp/mlab
    command: [./wait-for-mongo.sh]
    networks:
      - nginx-proxy
    depends_on:
      - mlab_mongo

  mlab_api_server:
    build: api_servers
    container_name: mlab_api_server
    environment:
      MLAB_MONGO_URI: "mongodb://mlab_mongo:27017/mlab?readPreference=primary"
    ports:
      - "9090:9090"
    depends_on:
      - mlab_init_mongo
    networks:
      - nginx-proxy

  mlab_api_server_2:
    build: api_servers
    container_name: mlab_api_server_2
    environment:
      MLAB_MONGO_URI: "mongodb://mlab_mongo:27017/mlab?readPreference=primary"
    depends_on:
      - mlab_init_mongo
    networks:
      - nginx-proxy

  mlab_nginx:
    image: nginx:latest
    container_name: mlab_nginx
    depends_on:
      - mlab_api_server
    expose:
      - "80"
    ports:
      - "80:80"
    volumes:
      - ./api_servers/nginx:/etc/nginx/conf.d
      - ./api_servers/swagger:/usr/share/nginx/html
    networks:
      - nginx-proxy

  mlab_dashboard:
    build: dashboard_server
    container_name: mlab_dashboard
    ports:
      - "5000:5000"
    networks:
      - nginx-proxy
    environment:
      - DATABASE_NAME=mlab
      - MLAB_MONGO_URI=mlab_mongo
    depends_on:
      - mlab_api_server
networks:
  nginx-proxy:
    driver: bridge